### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Prokopchini** [jasper-seinhorst/homebridge-homewizard-power-consumption#2]
hi. Do you think your plugin will fit this socket?

https://www.homewizard.com/shop/wi-fi-energy-socket/

**Comment by jasper-seinhorst** [comment]
Hi @Prokopchini, this plugin focusses on your overall power consumption. You can use [this plugin for Homewizard socket support](https://github.com/jvandenaardweg/homebridge-homewizard-energy-socket)
